---

- name: install nginx stable
  yum:
    name: nginx
    state: present

#- name: put test index file
#  template:
#    src: files/index.php
#    dest: /web/public_html/index.php
  
- name: Replace nginx config file
  template:
    src: files/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: start nginx service
  systemd:
    name: nginx
    state: started
    enabled: yes
