---

- name: install mariadb
  dnf:
    name: mariadb-server
    state: present

- name: Install needful soft
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - python3-pip
    - tar

- name: install pymysql python module via pip
  pip:
    name: pymysql
    state: present

- name: start mariadb service
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: Check if root password is set
  shell: >
    mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check

- name: Set MariaDB root password for the first time (root@localhost)
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host: "{{ item }}"
    login_unix_socket: "/var/lib/mysql/mysql.sock"
    state: present
  with_items:
    - ::1
    - 127.0.0.1
    - "{{ ansible_fqdn }}"
  when: root_pwd_check.rc == 0

- name: create a new database  
  mysql_db: 
    name: wordpress 
    state: present 
    login_user: root 
    login_password: "{{ mysql_root_password }}"  
