---

- name: Install Mariadb server
  dnf:
    name: mariadb-server
    state: present

- name: Install pymysql python module via pip
  pip:
    name: pymysql
    state: present

- name: Start mariadb service
  systemd:
    name: mariadb
    state: started
    enabled: yes

- name: Check if mysql root password is already set
  shell: >
    mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check

- name: If Mysql root password is no set yet, write root login credentials to ~/.my.chf
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: '0600'
  when: root_pwd_check.rc == 0

- name: If Mysql root password is no set yet, do it
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host: "{{ item }}"
    login_unix_socket: "/var/lib/mysql/mysql.sock"
    state: present
  with_items:
    - ::1
    - 127.0.0.1
    - localhost
  when: root_pwd_check.rc == 0

- name: Create a database for Wordpress installation  
  mysql_db: 
    name: wordpress 
    state: present 
    login_user: root 
    login_password: "{{ mysql_root_password }}"  
