---

- name: install nginx stable
  yum:
    name: nginx
    state: present

- name: Replace nginx config file
  template:
    src: files/nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: start nginx service
  systemd:
    name: nginx
    state: started
    enabled: yes
