---

- include_tasks: prepare_centos.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: install-nginx.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: install-phpfpm.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: install-mysql.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: install-wordpress.yml
  