---

- name: update all
  apt:
    name: "*"
    state: latest

- name: install nginx
  apt:
    name: nginx
    state: present

- name: copy index
  copy: src=index.php dest=/usr/share/nginx/html/index.php
  
- name: copy nginx.conf
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: reload nginx

- name: install php-fpm
  apt:
    name: php-fpm
    state: present

- name: copy php-fpm config
  copy: src=www.conf dest=/etc/php/7.4/fpm/pool.d/www.conf

- name: install mariadb
  apt:
    pkg:
      - mariadb-server
      - mariadb-client
      - python3-pymysql

- name: create my.cnf
  template:
    src: client.my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600  

- name: mysql root pass
  mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    login_user: root
    login_password: ""
    state: present