---

- name: Upgrade all packages
  dnf:
    name: '*'
    state: latest

- name: Install some packages
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - python3-pip
    - tar

- name: Set SELinux permissive mode
  selinux:
    policy: targeted
    state: permissive

- name: Open Nginx port
  firewalld:
    port: 80/tcp
    immediate: yes
    permanent: true
    state: enabled