---

- name: add new user 
  user: name="igor" password="321654" home="/home/igor" shell="/bin/bash"

- name: Upgrade all packages
  dnf:
    name: '*'
    state: latest

- name: Install needful soft
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - python3-pip
    - tar

- name: set selinux permissive mode
  selinux:
    policy: targeted
    state: permissive

- name: open http port
  firewalld:
    port: 80/tcp
    immediate: yes
    permanent: true
    state: enabled